import type { Metadata } from "next";
import "./globals.css";







export const metadata: Metadata = {
  title: {
    default: "This Sabbir Rahman",  // default
    template: "%s | SABBIR",  //%s will be replaced 
    absolute: "" // Its overright the defoult title segments

  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        
        {children}
      </body>
    </html>
  );
}
